# site settings
title: mjmdavis.com
description: A personal webpage.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mjmdavis.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mjmdavis
github_username: mjmdavis

# Build settings
markdown: kramdown
theme: minima
gems:
    - jekyll-feed
      #     - jekyll-assets
exclude:
    - Gemfile
    - Gemfile.lock
google_analytics: UA-98313079-1

# assets:
#     compress:
#         css: false
#         js: false
#     sources:
#         - _assets/bower
