# site settings
title: mjmdavis.com
description: A personal webpage.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mjmdavis.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mjmdavis
github_username: mjmdavis

# Build settings
markdown: kramdown
kramdown:
    parse_block_html: true
theme: minima
gems:
    - jekyll-feed
    - jekyll-jupyter-notebook
include:
    - .nojekyll
exclude:
    - Gemfile
    - Gemfile.lock
google_analytics: UA-98313079-1

